import = [
    #"~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
    "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[selection]
save_to_clipboard = true

[shell]
program = "/bin/zsh"
